import styled from 'styled-components'

export const Container = styled.div`
  position: fixed; /* Or absolute, depending on desired behavior */
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  display: flex;
  justify-content: center;
  align-items: center;
  z-index: 1000; /* Ensure it's above most other content */
  background-color: rgba(0, 0, 0, 0.3); /* Optional semi-transparent background */
  backdrop-filter: blur(2px); /* Optional blur effect */
  box-sizing: border-box;
`

export const CanvasContainer = styled.div`
  /* This container holds the P5 canvas */
  width: 100%; /* Take full space of the overlay */
  height: 100%;
  display: flex; /* Ensure canvas inside behaves correctly */
  justify-content: center;
  align-items: center;
  box-sizing: border-box;

  canvas {
    /* Style the canvas generated by P5 if needed */
    display: block; /* Prevent extra space below canvas */
    max-width: 100%;
    max-height: 100%;
  }
`